### PR TITLE
feat: add performance investigation

### LINKED ISSUE #8: Performance investigation [Rust]
Currently, this project is not Blazingly Fast 🚀 (despite the fact that it is written in Rust). An investigation to reveal what parts of the code make it slower would be pretty useful.

You can use something like [Criterion](https://github.com/bheisler/criterion.rs).

Keep in mind that the issue is for just the investigation! Changes are not really included in this (as for that I'd have to consider things like extra dependencies and whatnot). Creating the benchmarks and making a simple report is enough for this. In the case that an easy and important optimization is determined, after discussed I could definitely make this a separate issue.

### PR DESCRIPTION
**Pull request by ddanielsantos**
closes #8 

## details
Implemented a benchmark for the ``map_to_html`` function, to do it, i moved the content from ``src/util.rs`` to ``src/lib.rs`` (see [library crate](https://doc.rust-lang.org/book/ch12-03-improving-error-handling-and-modularity.html#splitting-code-into-a-library-crate))

I also tried to add a benchmark the ``download_blogs`` function, but the 100 iterations would take a lot of time:
```
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 1603.1s, or reduce sample count to 10.
Benchmarking map to html: Collecting 100 samples in estimated 1603.1 s (100 iterations)
```
I can reduce the iterations or try to figure out another solution, what do you think fits better?

### CODE REVIEW

**Comment by AntoniosBarotsis** [comment]
Made a small change to make adding more benchmarks easier.

The one you added works great and definitely shows that the performance bottleneck is in the HTTP calls.

I was thinking of adding a benchmark that just runs the code once for the downloads, that should be representative enough for me. I would be interested in getting a call heatmap for that.

I was looking into [pprof-rs](https://github.com/tikv/pprof-rs#integrate-with-criterion) but I keep getting compilation errors whenever I try to add it, wondering if you could get it to work somehow.

**Comment by ddanielsantos** [comment]
> I was thinking of adding a benchmark that just runs the code once for the downloads, that should be representative enough for me. (could you work on that?) I would be interested in getting a call heatmap for that.

Yeah, for sure, I'll dig more into the docs later and try to do this.

> Also let me know if you are participating in hacktober because in that case I'll merge this in a few days :)

Yes, I am. This project looks also btw, I'll try to contribute to it whenever possible.

**Comment by AntoniosBarotsis** [comment]
Another thing that might be useful is to be able to view download times per link (in case one specific website is disproportionately slow for some reason, it would be nice to know). Not sure how this would work with a proper benchmark lib (we could also just manually time the downloads) but just throwing ideas out there 👍

I basically want to have a good enough idea of what hinders performance before I decide whether I want async or not

**Comment by ddanielsantos** [comment]
I was searching about setting a lower number of samples for Criterion benchmarks (to bench the ``download_blog`` function) and discovered that the number of samples can't be ``< 10`` 

[here's the documentation about this](https://docs.rs/criterion/latest/criterion/struct.Criterion.html#method.sample_size)

running the bench with 10 samples resulted in this: 

```
Benchmarking download blogs/download blogs: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 204.2s.
download blogs/download blogs                                                                          
                        time:   [5.4904 s 7.1811 s 9.3531 s]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
```

what do you think?

**Comment by AntoniosBarotsis** [comment]
So the `< 10` limit makes sense for Criterion since it's supposed to be a "statistics-driven" benchmarking lib but this works fine for me.

We could increase the measurement time with [this](https://docs.rs/criterion/latest/criterion/struct.Criterion.html#method.measurement_time) function but I'm not sure if there's a reason to do that since that will always depend on a lot of external factors.

I think this is basically what I wanted! Could you push your work so I could take a look?

**Comment by AntoniosBarotsis** [comment]
*Converting this to a draft so I don't click the big green "Merge" button accidentally*

**Comment by AntoniosBarotsis** [comment]
Ok so, I made a per link benchmark and I found out that one of the feeds I was using is disproportionally slow which is interesting 

image

But that's about it, everything else is great, and thanks a lot for contributing!! I'll merge in 1-2 days to make sure the MR counts.

**Comment by AntoniosBarotsis** [comment]
I fixed some linting warnings I was getting after the introduction of `lib.rs`, thanks again!

**Comment by AntoniosBarotsis** [comment]
From the hacktober website `Your PR/MRs must be created between October 1 and October 31 (in any time zone, UTC-12 thru UTC+14).` so just merging it after the 1st doesn't count. You might want to update your local branch and create another MR.

**Comment by ddanielsantos** [comment]
Oh no 😅, ok I'll do it. Thanks again man, if you find  any other issue someday, feel free to contact me

**Comment by AntoniosBarotsis** [comment]
waiting for the MR again 👀

**Comment by ddanielsantos** [comment]
done 🫡

**Pull request closed without merging**
