### PR TITLE
Add tests for `get_page`.

### PR DESCRIPTION
**Pull request by Kineolyan**
This writes one basic test for `get_page`, using a valid URL.
In addition, to add some security because the reader expects XML, I added some validition on the content type returned along the body.
This created additional tests regarding downloading another type of text (html) and non-text (image).

Tell me if you need more on this particular function.

---

Related to #9

### CODE REVIEW

**Comment by Kineolyan** [comment]
Cool that you liked it :smiley: 

I am working on the tests for the parsing. But these are a bit more complex as I have to dive into the spec for Atom feeds

**Comment by AntoniosBarotsis** [comment]
Oh I didn't realize and just went ahead and merged 0_0

Can open another one I guess

**Comment by Kineolyan** [comment]
That's ok. I was planning on doing it in a separate PR (work habit) as they were different topics

And BTW, I just saw your changes [c7cfa8d](https://github.com/AntoniosBarotsis/Rss2Email/pull/15/commits/c7cfa8d58161d7632f6a62fb5a72f33bd193b1cb). Thanks, today I learned something

**Comment by AntoniosBarotsis** [comment]
I've been using linting like crazy, which has helped me immensely being very new to the language. I don't know if you are using visual studio code (you can probably do this in any editor) but assuming you have the [Rust Analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) extension and Clippy installed, you can put "Clippy" in the following setting section and you'll be getting these warnings in your code editor directly:

image

I have a pretty verbose linting config defined [here](https://github.com/AntoniosBarotsis/Rss2Email/blob/master/.cargo/config.toml) so you are bound to learn something new with that lmao

**Pull request merged**
