### PR TITLE
Added env variable use if feeds.txt not specified.

### PR DESCRIPTION
**Pull request by oliviacarino**
Note: to run with environment variables, use the following command:
`cargo run -- link1*link2*linkn`  where each link has the format `https://website.com/file.xml`

Each link is delimited by a `*` which can easily be changed if needed. I tried using `;` but had some issues with it being read correctly. I've tested the code passing the same feed links from `feeds.txt` as env variables and the output matched the same as when using the `feeds.txt` file (`cargo run` is used).

### CODE REVIEW

**Review by AntoniosBarotsis — CHANGES_REQUESTED** [review]
Could you resolve the merge conflicts?

It would also be useful if the argument was named (something like `--feeds feed1*feed2`) in case I decide to add more in the future. Maybe you find [clap](https://docs.rs/clap/latest/clap/) useful for this.

**Comment by oliviacarino** [comment]
Will fix these today!

**Review by oliviacarino — COMMENTED** [review]
Still working on merge conflicts

**Comment by oliviacarino** [comment]
@AntoniosBarotsis done! Had to move the modified funcs from util.rs to the new file lib.rs

**Comment by AntoniosBarotsis** [comment]
I made a few changes as what I had in mind was a bit simpler but thanks :)

**Review by AntoniosBarotsis — COMMENTED** [review]
Adding reviews for consistency.

**Review by AntoniosBarotsis — COMMENTED** [review]
Resolved

**Pull request merged**
